// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAST5O_JqTdo5W8b3Yp3-JBON0H-RKyH6I',
    appId: '1:850017519173:web:cb0f44ff606b78bad1052c',
    messagingSenderId: '850017519173',
    projectId: 'chatappflutter-eff9e',
    authDomain: 'chatappflutter-eff9e.firebaseapp.com',
    storageBucket: 'chatappflutter-eff9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvk5MLvSvyal34DfCc9NUQP5LvJv85xVk',
    appId: '1:850017519173:android:c8737afb44a12d4dd1052c',
    messagingSenderId: '850017519173',
    projectId: 'chatappflutter-eff9e',
    storageBucket: 'chatappflutter-eff9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEoFeBjU3uKyYG47ryczUp4k6UHBg0Zo4',
    appId: '1:850017519173:ios:0ee1260d1078df8ed1052c',
    messagingSenderId: '850017519173',
    projectId: 'chatappflutter-eff9e',
    storageBucket: 'chatappflutter-eff9e.appspot.com',
    iosClientId: '850017519173-7f0tos6vdatf4lma45cavcuv7s0n15il.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
